import type { Metadata } from "next";
import "./globals.css";
import Chakra from "@/components/Chakra";
import Script from "next/script";
import localFont from 'next/font/local';
const inter = localFont({
  src: '../app/fonts/inter.ttf',
  weight: '400',
  variable: '--font-inter' 
});
export const metadata: Metadata = {
  title: "Blog Wave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="icon" href="./favicon.ico" />
        <Chakra>
        {children}
        </Chakra>
         <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/jquery.ripples@0.6.3/dist/jquery.ripples.min.js" strategy="lazyOnload" />
        </body>
    </html>
  );
}
